services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    image: mariadb
    env_file: 
      - .env
    secrets:
      - db_user_password
      - db_root_password
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "mariadb -u root --password=$(cat /run/secrets/db_root_password) -e 'SELECT 1'"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
  
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    image: wordpress
    env_file:
      - .env
    secrets:
      - db_user_password
      - wp_user_password
      - wp_admin_password
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: on-failure
    depends_on:
      mariadb:
        condition: service_healthy


secrets:
  db_user_password:
    file: ../secrets/db_user_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/db
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress

networks:
  inception:
    driver: bridge
    name: inception
