NoAnonymous                 yes
ChrootEveryone              yes
PassivePortRange            30000 30009
MaxClientsNumber            5
MaxClientsPerIP             5
VerboseLog                  yes
ProhibitDotFilesRead        no
ProhibitDotFilesWrite       no
MinUID                      1000
TLS                         0
